version: '3.2'

services:

  db:
    image: postgres:latest
    env_file:
      - server/.env-none-dev
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=log"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d twitter -U admin" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    volumes:
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db/data:/var/lib/postgresql/data
    networks:
      - my_network


  db_test:
    image: postgres:latest
    environment:
      - POSTGRES_DB=twitter_test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PG_DATA=/var/lib/postgresql/pgdata
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=log"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d twitter -U admin" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5433:5432'
    networks:
      - my_network

networks:
  my_network:
    driver: bridge