version: '3.2'

services:

  db:
    image: postgres:latest
    env_file:
      - server/.env-none-dev
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=log"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d twitter -U admin" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    volumes:
      - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db/data:/var/lib/postgresql/data
    networks:
      - my_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - server/.env-none-dev
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_started
    networks:
      - my_network


networks:
  my_network:
    driver: bridge